services:
  app:
    build: .
    container_name: nestjs_20
    ports:
      - "3000:3000"  # Maps port 3001 to the host
    networks:
      - node-network
    volumes:
      - .:/usr/src/app
  student:
    build: .
    container_name: nestjs_student
    ports:
      - "3001:3001"  # Maps port 3001 to the host
    networks:
      - node-network
    volumes:
      - .:/usr/src/app
  subject:
    build: .
    container_name: nestjs_subject
    ports:
      - "3002:3002"  # Maps port 3001 to the host
    networks:
      - node-network
    volumes:
      - .:/usr/src/app
networks:
  node-network:
    driver: bridge
