services:
  rabbitmq:
    image: "rabbitmq:management"
    container_name: "rabbitmq"
    hostname: "rabbitmq"
    restart: always
    networks:
      - my_network
    ports:
      - "5672:5672"
      - "15672:15672"

  app:
    build: .
    container_name: nestjs_25
    ports:
      - "3000:3000"  # Maps port 3001 to the host
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
    networks:
      - my_network
  student:
    build: .
    container_name: nestjs_student
    ports:
      - "3001:3001"  # Maps port 3001 to the host
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
  subject:
    build: .
    container_name: nestjs_subject
    ports:
      - "3002:3002"  # Maps port 3001 to the host
    networks:
      - my_network
    volumes:
      - .:/usr/src/app
networks:
  my_network:
    driver: bridge
